library(readr)
library(dplyr)
library(tidyr)
library(tibble)
library(stringr)
library(universalmotif)

### load motifs
CPEs <- read_meme('../data/misc/CPEs.meme')
TFs <- read_meme('../data/misc/TF-clusters.meme')

### load sequences (using the promoter annotation file generated by `promoter_annotation/extract_promoter_seqs.sh`)
all.sequences <- bind_rows(
  'At' = read_tsv('../data/promoter_annotation/Arabidopsis_all_promoters_unique.tsv'),
  'Zm' = read_tsv('../data/promoter_annotation/Maize_all_promoters_unique.tsv'),
  'Sb' = read_tsv('../data/promoter_annotation/Sorghum_all_promoters_unique.tsv'),
  .id = 'sp')

all.seqs <- Biostrings::DNAStringSet(deframe(select(all.sequences, gene, sequence)))

all.species <- deframe(select(all.sequences, gene, sp))

### scan sequences for maximum motif score
# first, find any (p-value threshold of 1) occurrence of the motif in each sequence, then keep only the one with the highest score for each sequence

## TATA
motif <- 'TATA'

TATA.scores <- as_tibble(scan_sequences(filter_motifs(CPEs, altname = motif), all.seqs, threshold = 1, nthreads = 0)) %>%
  group_by(sequence) %>%
  filter(score == max(score)) %>%
  ungroup() %>%
  mutate(
    rel.score = (score - min.score) / (max.score - min.score),
    element = motif
  ) %>%
  rename('gene' = sequence) %>%
  inner_join(
    select(all.sequences, gene, sequence),
    by = 'gene'
  ) %>%
  mutate(
    # extract the sequences up- and downstream of the 8 bp core of the TATA-box to scan for the BREu and BREd elements
    sp = all.species[gene],
    upstream = str_sub(paste0('GCTG', sequence), start - 4 + 4, start + 3 + 4),
    downstream = str_sub(paste0(sequence, case_when(sp == 'At' ~ 'TCTC', sp == 'Zm' ~ 'CCCG', sp == 'Sb' ~ 'TACC')), stop - 3, stop + 3)
  )

up.seqs <- Biostrings::DNAStringSet(deframe(select(TATA.scores, gene, upstream)))
down.seqs <- Biostrings::DNAStringSet(deframe(select(TATA.scores, gene, downstream)))

TATA.scores <- TATA.scores %>%
  group_by(gene, element) %>%
  summarise(
    rel.score = max(rel.score)
  ) %>%
  ungroup()

## core promoter elements
# for the two initiator elements (Inr and TCT), only the region of the annotated TSS is analyzed
# for the TFIIB recognition elements (BREu and BREd), only the bases up- or downstream of the highest scoring TATA-box are considered
# this is done for each motif separately to conserve memory
for (motif in CPEs) {
  motif.name <- motif['altname']
  if (motif.name == 'TATA') {
    next
  } else if (motif.name == 'Inr') {
    test.seqs <- Biostrings::DNAStringSet(all.seqs, start = 160, end = 170)
  } else if (motif.name == 'TCT') {
    test.seqs <- Biostrings::DNAStringSet(all.seqs, start = 164, end = 170)
  } else if (motif.name == 'BREu') {
    test.seqs <- up.seqs
  } else if (motif.name == 'BREd') {
    test.seqs <- down.seqs
  } else {
    test.seqs <- all.seqs
  }
  
  scores <- as_tibble(scan_sequences(motif, test.seqs, threshold = 1, nthreads = 0)) %>%
    group_by(gene = sequence, max.score, min.score) %>%
    summarise(
      score = max(score),
      .groups = 'drop'
    ) %>%
    mutate(
      rel.score = (score - min.score) / (max.score - min.score),
      element = motif.name
    ) %>%
    select(gene, element, rel.score)
  
  assign(paste0(motif.name, '.scores'), scores)
}

# combine scores for all CPE motifs
CPE.names <- sapply(CPEs, function (x) x['altname'])

CPE.scores <- bind_rows(mget(paste0(CPE.names, '.scores'))) %>%
  pivot_wider(
    names_from = element,
    values_from = rel.score
  ) %>%
  mutate(
    across(everything(), replace_na, 0)
  )

rm(list = paste0(CPE.names, '.scores'))

## TF-clusters
for (motif in TFs) {
  motif.name <- motif['name']
  
  scores <- as_tibble(scan_sequences(motif, all.seqs,  RC = TRUE, threshold = 1, nthreads = 0)) %>%
    group_by(gene = sequence, max.score, min.score) %>%
    summarise(
      score = max(score),
      .groups = 'drop'
    ) %>%
    mutate(
      rel.score = (score - min.score) / (max.score - min.score),
      element = motif.name
    ) %>%
    select(gene, element, rel.score)
  
  assign(paste0(motif.name, '.scores'), scores)
}

# combine scores for all TF motifs
TF.names <- sapply(TFs, function (x) x['name'])

TF.scores <- bind_rows(mget(paste0(TF.names, '.scores'))) %>%
  pivot_wider(
    names_from = element,
    values_from = rel.score
  ) %>%
  rename_with(~ gsub('-cluster', '', .x, fixed = TRUE), starts_with('TF'))

rm(list = paste0(TF.names, '.scores'))

### combine TF and CPE scores and save file
all.scores <- full_join(CPE.scores, TF.scores, by = 'gene') %>%
  mutate(
    across(where(is.numeric), round, 5) # lower precision to reduce file size
  )

write_tsv(all.scores, 'motifs/motif-scores.tsv.gz')
